GENOME_VERSION = "GRCh38"
ENSEMBL_VERSION = "81"
ENSEMBL_VERSION_SNPEFF = "86"
GENEMODEL_VERSION = GENOME_VERSION + "." + ENSEMBL_VERSION
GENEMODEL_VERSION_SNPEFF = GENOME_VERSION + "." + ENSEMBL_VERSION_SNPEFF
GENOME_FA = f"data/ensembl/Homo_sapiens.{GENOME_VERSION}.dna.primary_assembly.fa"
ENSEMBL_GFF = f"data/ensembl/Homo_sapiens.{GENEMODEL_VERSION}.gff3"
FA=GENOME_FA # for analysis; can also be TEST_GENOME_FA
GFF3=ENSEMBL_GFF # for analysis; can also be TEST_ENSEMBL_GFF
UNIPROTXML="data/uniprot/human.protein.xml.gz" #"data/Homo_sapiens_202022.xml.gz"
UNIPROTFASTA="data/uniprot/human.protein.fasta" #"data/Homo_sapiens_202022.xml.gz"

# SETTINGS
configfile: "config.yaml"
q=[20] #skewer filter value; can test other values if needed

rule all:
    input:
        expand("data/{q}/combined.spritz.snpeff.protein.withmods.xml.gz", q=q), # variants
        "data/GRCh38.86.protein.withmods.xml.gz" # reference

include: "rules/downloads.smk"
include: "rules/align.smk"
include: "rules/variants.smk"
include: "rules/proteogenomics.smk"
include: "rules/qc.smk"
