configfile: "config.yaml"
include: "rules/common.smk"

rule all:
    input: all_output # see common.smk

rule clean:
    log: "{dir}/clean.log"
    conda: "environments/basic.yaml"
    shell:
        "rm -rf data/ ChromosomeMappings/ SnpEff/ tmp/ fast.tmp/ && "
        "cd GtfSharp && dotnet clean && cd .. && "
        "cd TransferUniProtModifications && dotnet clean && cd .. 2> {log}"

rule update_message:
    output: "{dir}/please_update_spritz.txt"
    log: "{dir}/please_update_spritz.log"
    conda: "environments/basic.yaml"
    shell: "echo \"Please update Spritz at https://github.com/smith-chem-wisc/Spritz/releases\" > {output} 2> {log}"

rule prose:
    output: "{dir}/prose.txt"
    log: "{dir}/prose.log"
    conda: "environments/basic.yaml"
    shell: "python scripts/prose.py {output} 2> {log}"

rule setup:
    input:
        f"ChromosomeMappings/{config['genome']}_UCSC2ensembl.txt",
        f"data/ensembl/{config['species']}.ensembl.vcf",
        TRANSFER_MOD_DLL,
        UNIPROTFASTA,
        UNIPROTFASTA,
        FA,
        "ptmlist.txt",
        "PSI-MOD.obo.xml",
        "SnpEff/snpEff.jar",
        [] if not check('sra') else expand(["{dir}/{sra}_1.fastq", "{dir}/{sra}_2.fastq"], dir=config['analysisDirectory'], sra=config['sra']),
        [] if not check('sra_se') else expand(["{dir}/{sra_se}.fastq"], dir=config['analysisDirectory'], sra_se=config['sra_se'])
    output: "data/setup.txt"
    log: "data/setup.log"
    conda: "environments/setup.yaml"
    shell: "touch {output}"

include: "rules/downloads.smk"
include: "rules/align.smk"
include: "rules/variants.smk"
include: "rules/isoforms.smk"
include: "rules/proteogenomics.smk"
include: "rules/quant.smk"
