"""Regenerate genomes.csv from Ensembl, so nobody has to hand-maintain it.

Run it with no arguments to add the newest release and refresh the file in place:

    python update_genomes.py            # newest release only
    python update_genomes.py --min-release 105   # backfill older releases too

Rows already in the file are kept, so saved reference strings keep working.

Assembly names come from the actual gff3 directory listings rather than from the
species_EnsemblVertebrates.txt summary, because the summary disagrees with the filenames
for some species - in release 116 it reports sorAra1 and UOA_Wagyu_1 where the files are
named COMMON_SHREW1 and ASM4028618v1. Only the common name is taken from the summary.

A species is left out when its gene set version differs from the Ensembl release, because
Spritz builds the GFF3 URL as {ref}.{release}.gff3.gz and that file will not exist. In
release 116 that is caenorhabditis_elegans, drosophila_melanogaster and
saccharomyces_cerevisiae, all numbered 63 - Ensembl imports those from WormBase, FlyBase
and SGD. Listing them would hand the user a reference that fails partway into a run.
"""

import argparse
import csv
import io
import os
import re
import sys
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed

FTP_ROOT = "https://ftp.ensembl.org/pub"
SUMMARY = "species_EnsemblVertebrates.txt"
DEFAULT_CSV = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "SpritzBackend", "genomes.csv")

HEADER = [
    "# Generated by workflow/scripts/update_genomes.py from the Ensembl FTP listings.",
    "# Do not edit by hand - rerun the script instead.",
    "# Columns: release,species,common name,genome assembly",
]

PATCH_SUFFIX = re.compile(r"\.p\d+$")


def strip_patch(assembly):
    """Drop an assembly patch suffix, e.g. GRCh38.p14 -> GRCh38.

    Ensembl reports the patched assembly name in the summary file but names the FASTA and
    GFF3 files after the unpatched one, so keeping the suffix yields URLs that 404. Human
    is currently the only species affected, which is exactly why it is easy to miss.
    """
    return PATCH_SUFFIX.sub("", assembly)


def sanitise(field):
    """Make a field safe for a file that is parsed by splitting on commas.

    Spritz reads genomes.csv with a plain String.Split(','), and a reference string is
    required to have exactly four elements, so an embedded comma turns a valid row into a
    rejected one. Release 116 has one: "Caenorhabditis elegans (Nematode, N2)".
    """
    return field.replace(",", ";").strip()


def fetch(url):
    with urllib.request.urlopen(url, timeout=120) as response:
        return response.read().decode("utf-8", errors="replace")


def available_releases(minimum):
    """Release numbers Ensembl currently serves, newest last."""
    listing = fetch(FTP_ROOT + "/")
    found = {int(n) for n in re.findall(r"release-(\d+)", listing)}
    return sorted(n for n in found if n >= minimum)


GFF3_NAME = re.compile(r"([A-Z][A-Za-z0-9_]+)\.([A-Za-z0-9_.\-]+)\.(\d+)\.gff3\.gz")


def common_names(release):
    """species -> common name, from the per-release summary file."""
    text = fetch(f"{FTP_ROOT}/release-{release}/{SUMMARY}")
    names = {}
    for record in csv.reader(io.StringIO(text), delimiter="\t"):
        if record and not record[0].startswith("#") and len(record) > 1:
            names[record[1]] = sanitise(record[0]).lower()
    return names


def assembly_from_listing(release, species):
    """The assembly and gene set version Ensembl actually uses in this species' filenames.

    The summary file's assembly column cannot be trusted for this: in release 116 it reports
    sorAra1 for sorex_araneus and UOA_Wagyu_1 for bos_taurus_wagyu, while the files are named
    COMMON_SHREW1 and ASM4028618v1. The directory listing is the source of truth.
    """
    try:
        html = fetch(f"{FTP_ROOT}/release-{release}/gff3/{species}/")
    except Exception:
        return None
    for match in GFF3_NAME.finditer(html):
        _, assembly, version = match.groups()
        if ".chromosome." in match.group(0) or ".abinitio." in match.group(0):
            continue
        return strip_patch(assembly), version
    return None


def rows_for_release(release, workers=12, skipped=None):
    """(release, species, common name, assembly) for every species Spritz can download.

    Species whose gene set version differs from the Ensembl release are left out: Spritz
    builds the GFF3 URL as {ref}.{release}.gff3.gz, so for caenorhabditis_elegans, whose
    release-116 files are numbered 63, that URL does not exist. Listing them would only
    offer the user a reference that fails partway into a run.
    """
    names = common_names(release)
    listing = fetch(f"{FTP_ROOT}/release-{release}/gff3/")
    species_dirs = sorted({s for s in re.findall(r'href="([a-z0-9_]+)/"', listing) if s in names})

    rows = []
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = {pool.submit(assembly_from_listing, release, s): s for s in species_dirs}
        for future in as_completed(futures):
            species = futures[future]
            found = future.result()
            if not found:
                if skipped is not None:
                    skipped.append((release, species, "no gff3 found"))
                continue
            assembly, version = found
            if version != str(release):
                if skipped is not None:
                    skipped.append((release, species, f"gene set version {version}"))
                continue
            rows.append((f"release-{release}", species, names[species], assembly))
    return sorted(rows, key=lambda r: r[1])


def read_existing(path):
    """Existing non-comment rows, so historical releases are not dropped.

    Someone may have a saved reference string naming a release Ensembl no longer indexes,
    and those downloads still resolve, so removing the rows would break them for no gain.
    """
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as handle:
        return [tuple(line.rstrip("\n").split(",")) for line in handle if line.strip() and not line.startswith("#")]


def release_number(row):
    return int(row[0].split("-")[1])


def build(existing, fetched):
    """Merge, preferring freshly fetched rows, ordered by release then species."""
    merged = {(row[0], row[1]): row for row in existing}
    merged.update({(row[0], row[1]): row for row in fetched})
    return sorted(merged.values(), key=lambda row: (release_number(row), row[1]))


def write(path, rows):
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        for line in HEADER:
            handle.write(line + "\n")
        for row in rows:
            handle.write(",".join(row) + "\n")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=DEFAULT_CSV)
    parser.add_argument("--min-release", type=int, default=None,
                        help="oldest release to fetch (default: newest only); rows already in the file are kept")
    args = parser.parse_args(argv)

    newest = available_releases(0)[-1]
    releases = available_releases(args.min_release) if args.min_release else [newest]
    if not releases:
        print("No releases found on the Ensembl FTP listing.", file=sys.stderr)
        return 1
    print(f"Fetching {len(releases)} releases: {releases[0]}-{releases[-1]}", file=sys.stderr)

    fetched, skipped = [], []
    for release in releases:
        rows = rows_for_release(release, skipped=skipped)
        print(f"  release-{release}: {len(rows)} species", file=sys.stderr)
        fetched.extend(rows)
    for release, species, why in sorted(skipped):
        print(f"  skipped release-{release} {species}: {why}", file=sys.stderr)

    existing = read_existing(args.output)
    rows = build(existing, fetched)
    write(args.output, rows)
    print(f"Wrote {len(rows)} rows ({len(existing)} before) to {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
