name: Build and test Docker

on:
  push:
    branches: [ PrefetchAndVariants ]
  pull_request:
    branches: [ PrefetchAndVariants ]
  schedule:
    - cron: '0 4 * * 1'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup Docker
      uses: docker/build-push-action@v2
      with :
        context: Spritz/
        tags: test-image:latest
        push: false

    - name: Run test image
      uses: addnab/docker-run-action@v3
      with:
        image: test-image:latest
        run: /opt/conda/lib/dotnet/dotnet SpritzCMD.dll -a=/app/spritz/results/ -b -c -d -r="release-97,homo_sapiens,human,GRCh38" -p=8 -s=SRR629563