name: Build and test

on:
  push:
    branches: [ PrefetchAndVariants ]
  pull_request:
    branches: [ PrefetchAndVariants ]
  schedule:
    - cron: '0 4 * * 1'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore Spritz/Spritz.sln

    - name: Build
      run: dotnet build --no-restore /p:Platform=x64 Spritz/Spritz.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal Spritz/Spritz.sln

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Installer
      run: msbuild Spritz/SpritzInstaller/SpritzInstaller.wixproj /p:Configuration=Release /p:UseSharedCompilation=false

    - name: Setup Docker
      uses: docker/build-push-action@v2
      with :
        context: Spritz/
        tags: test-image:latest
        push: false

    - name: Run test image
      uses: addnab/docker-run-action@v3
      with:
        image: test-image:latest
        run: /opt/conda/lib/dotnet/dotnet SpritzCMD.dll -a=/app/spritz/results/ -b -c -d -r="release-97,homo_sapiens,human,GRCh38" -p=8 -s=SRR629563
