name: Build and test Docker

on:
  push:
    branches: [ PrefetchAndVariants ]
  pull_request:
    branches: [ PrefetchAndVariants ]
  schedule:
    - cron: '0 4 * * 1'

jobs:
  buildx:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore Spritz/SpritzCMD/SpritzCMD.csproj

    - name: Build
      run: dotnet build --no-restore /p:Platform=x64 --configuration Release Spritz/SpritzCMD/SpritzCMD.csproj

      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup Docker
      uses: docker/build-push-action@v2
      with :
        context: ./Spritz/
        tags: test-image:latest
        push: false

    - name: Run test image
      uses: addnab/docker-run-action@v3
      with:
        image: test-image:latest
        run: /opt/conda/lib/dotnet/dotnet SpritzCMD.dll -a=/app/spritz/results/ -r="release-97,homo_sapiens,human,GRCh38" -p=8 -s=SRR629563