name: Release Docker image

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  buildx:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore Spritz/SpritzCMD/SpritzCMD.csproj

    - name: Build
      run: dotnet build --no-restore /p:Platform=x64 --configuration Release Spritz/SpritzCMD/SpritzCMD.csproj

    - name: Build
      run: dotnet build --no-restore /p:Platform=x64 --configuration Release Spritz/SpritzCMD/SpritzCMD.csproj

    - name: Build docker image
      run: docker build -t spritz ./Spritz/

    - name: Run test
      run: docker run --user=root spritz /opt/conda/lib/dotnet/dotnet SpritzCMD.dll -a=/app/spritz/results/ -r="release-97,homo_sapiens,human,GRCh38" -p=4

    - name: Login, tag, and push
      run: |
        docker login -u ${env.username} -p ${env.password}
        $version=&git describe --tags
        docker tag spritz smithlab/spritz:${version}
        docker push smithlab/spritz:${version}
      env:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
