name: Release installer, SpritzCMD

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Verify commit exists in release branch
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/${env:RELEASE_BRANCH}
        env:
          RELEASE_BRANCH: PrefetchAndVariants

      - name: Restore dependencies
        run: dotnet restore Spritz/Spritz.sln
      - name: Build
        run: |
          $version= &git describe --tags
          dotnet build --no-restore --configuration Release /p:Version=${version} /p:Platform=x64 
      - name: Test
        run: |
          $version= &git describe --tags
          dotnet test --configuration Release /p:Platform=x64 /p:Version=${version} --no-build

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Build Installer
        run: |
          $version= &git describe --tags
          msbuild Spritz/SpritzInstaller/SpritzInstaller.wixproj  /p:Configuration=Release /p:Version=${version}

      - name: Create archive
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'SpritzCMD.zip'
          directory: Spritz/SpritzCMD/bin/x64/Release/net5.0/

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SpritzCMD.zip,Spritz/SpritzInstaller/bin/Release/Spritz.msi"
          token: ${{ secrets.UPLOAD_TOKEN }}
